/*
 * generated by Xtext
 */
package ch.vorburger.xobjects.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IGenerator
import org.eclipse.xtext.generator.IFileSystemAccess

class XObjectsGenerator implements IGenerator {
	// TODO create a XObjectsJSONGenerator, and an abstract base class shared with XObjectsJavaGenerator etc.
	 
	override void doGenerate(Resource resource, IFileSystemAccess fsa) {
		//TODO implement me
	}
}
