/*
* generated by Xtext
*/
package ch.vorburger.xobjects.ui.contentassist;

import ch.vorburger.xobjects.ui.contentassist.AbstractXObjectsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XObjectsProposalProvider extends AbstractXObjectsProposalProvider {

}
