/*
 * generated by Xtext
 */
package ch.vorburger.xobjects.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XObjectsUiModule extends ch.vorburger.xobjects.ui.AbstractXObjectsUiModule {
	public XObjectsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
