/*
 * generated by Xtext
 */
package ch.vorburger.xobjects;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XObjectsRuntimeModule extends ch.vorburger.xobjects.AbstractXObjectsRuntimeModule {

}
